### PR TITLE
Force code object v2

### PR DESCRIPTION
**Pull request by kzhuravl**

### CODE REVIEW

**Comment by atamazov** [comment]
Just in case - I guess this breaks backward compatibility with previous rocm versions.

**Comment by kzhuravl** [comment]
@atamazov, I do not think it does?

compiler will just ignore unknown features and proceed with compilation. example:

```
clang -target amdgcn-amd-amdhsa -mcpu=fiji -Xclang -target-feature -Xclang -my-unknown-made-up-feature test.cl -o test.so
'-my-unknown-made-up-feature' is not a recognized feature for this target (ignoring feature)
'-my-unknown-made-up-feature' is not a recognized feature for this target (ignoring feature)
'-my-unknown-made-up-feature' is not a recognized feature for this target (ignoring feature)
'-my-unknown-made-up-feature' is not a recognized feature for this target (ignoring feature)
```

**Comment by dagamayank** [comment]
I don’t think it is a good idea to just start throwing those warnings suddenly.

**Comment by atamazov** [comment]
@kzhuravl For CO v3 auto-detection we are currently using the feature that compiler _fails_ if unknown option is passed:
```C++
static bool GcnAssemblerSupportsOption(const std::string& option)
{
    auto p = boost::filesystem::temp_directory_path() / boost::filesystem::unique_path();
    miopen::WriteFile(miopen::GetKernelSrc("dummy_kernel"), p);
    auto src = p.string();
    try
    {
        AmdgcnAssembleQuiet(src, "-mcpu=gfx900 " + option);
        MIOPEN_LOG_I("Supported: '" << option << '\'');
        return true;
    }
    catch(...)
    {
        MIOPEN_LOG_I("Not supported: '" << option << '\'');
        return false;
    }
}

static bool GcnAssemblerSupportsCOv3()
{
    const static bool b = GcnAssemblerSupportsOption("-mno-code-object-v3");
    return b;
}
```
If this change, the CO v3 support in the assembler wold be broken. This could be fixed, but backward compatibility would be lost in turn.

**Comment by atamazov** [comment]
BTW seems like this PR enforces ___v3___, not v2, right?

**Comment by dagamayank** [comment]
Yes, that is my impression as well that it is v3.

**Comment by kzhuravl** [comment]
> If this change, the CO v3 support in the assembler wold be broken. This could be fixed, but backward compatibility would be lost in turn.

clang-ocl does not invoke the assembler separately. so there is no need to use the "-mno-code-object-v3" option here, which was introduced because of assembler. So how would the assembler be broken in this scenario?


> BTW seems like this PR enforces v3, not v2, right?

"code-object-v3" is the llvm target feature, the first dash is actually the minus, so you are basically saying "disable code object v3".

If you want to enable v3, you will use plus:
-Xclang -target-feature -Xclang +code-object-v3

**Comment by atamazov** [comment]
@kzhuravl 
>> If this change, the CO v3 support in the assembler wold be broken. This could be fixed, but backward compatibility would be lost in turn.
>
> clang-ocl does not invoke the assembler separately. so there is no need to use the "-mno-code-object-v3" option here, which was introduced because of assembler. So how would the assembler be broken in this scenario?

I was wrong.

**Comment by atamazov** [comment]
@kzhuravl 
> "code-object-v3" is the llvm target feature, the first dash is actually the minus, so you are basically saying "disable code object v3".

I've forgotten that, thanks for the reminder.

**Comment by atamazov** [comment]
This looks good to me.

**Pull request merged**
