### PR TITLE
Switch clang-ocl dependency on rocm-dev package

### PR DESCRIPTION
**Pull request by aaronenyeshi**
Replace package dependency on opencl with rocm-dev which includes either hcc or hip-clang.

### CODE REVIEW

**Comment by aaronenyeshi** [comment]
Should we switch the package dependency on rocm-dev which is used by math libs, to allow the package to depend on installation of either hcc or hip-clang's llvm-amdgpu?

**Comment by pfultz2** [comment]
It should depende directly on the compiler and device libs, and not use the metapackage(which can bring in requirements we may not want).

**Comment by aaronenyeshi** [comment]
It seems DPKG has the functionality to add DEPENDS "hcc | llvm-amdgpu". But RPM doesn't have the ability to do that. Instead RPM rather we use PROVIDES to say llvm-amdgpu PROVIDES hcc, which I think might be unsafe.

**Comment by aaronenyeshi** [comment]
Closing old prs

**Pull request closed without merging**
