### PR TITLE
rename package llvm-amdgpu to rocm-llvm

### PR DESCRIPTION
**Pull request by david-salinas**

### CODE REVIEW

**Review by pramenku — APPROVED** [review]
LGTM

**Review by atamazov — CHANGES_REQUESTED** [review]
This would break backward compatibility with previous ROCm versions, isn't it?

**Review by pfultz2 — APPROVED** [review]

**Comment by david-salinas** [comment]
> This would break backward compatibility with previous ROCm versions, isn't it?
@atamazov  We've added a "Provides: llvm-amdgpu" to the new rocm-llvm packages, so that other packaged that depend on that name will have that dependency fulfilled.

**Comment by atamazov** [comment]
@david-salinas 
> @atamazov We've added a "Provides: llvm-amdgpu" to the new rocm-llvm packages, so that other packaged that depend on that name will have that dependency fulfilled.

So the old clang-ocl will be able to work with the new versions of ROCm. This is good.

But I mean the case when the new clang-ocl is used with previous ROCm, -- the one that does not provide "rocm-llvm". Example case is MIOpen which is able to work with old ROCm versions. If we update MIOpen deps to include fresh clang-ocl, then that compatibility would be broken.

Most likely this is not an issue becase MIOpen can continue using "old" clang-ocl.

**Comment by david-salinas** [comment]
> But I mean the case when the new clang-ocl is used with previous ROCm, -- the one that does not provide "rocm-llvm". Example case is MIOpen which is able to work with old ROCm versions. If we update MIOpen deps to include fresh clang-ocl, then that compatibility would be broken.

Hi @atamazov, So AFAICT, MIOpen just looks to see if clang-ocl is installed.  And then it has a requirement for a specific SHA commit hash in clang-ocl.  But changing the name of llvm-amdgpu to rocm-llvm shouldn't affect MIOpen, since that is a dependency clang-ocl has. 

I do see a reference to package name "llvm-amdgpu" in the MIOpen Dockerfile - but because we have the "Provides: llvm-amdgpu" in the rocm-llvm package, we should be fine ... until we remove that Provides: llvm-amdgpu in an upcoming release.

> 
> Most likely this is not an issue becase MIOpen can continue using "old" clang-ocl.

Yup, I think MIOpen will be fine, even using an old clang-ocl.

**Comment by atamazov** [comment]
Okay.

[Informative]
> So AFAICT, MIOpen just looks to see if clang-ocl is installed. 

Well, not exactly so. It is documented that `install_deps.cmake` can be used to install deps for MIOpen. And that file is referring to `requirements.txt`, which contains today:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/fca9fed0b571b1b8ff587f25a75221d36e62e8b0/requirements.txt#L3

**Review by atamazov — APPROVED** [review]

**Pull request merged**
